module.exports = {
  'docs/spec/alignment.md': require('../docs/spec/alignment.md'),
  'docs/spec/colors.md': require('../docs/spec/colors.md'),
  'docs/spec/contrast.md': require('../docs/spec/contrast.md'),
  'docs/spec/direct.md': require('../docs/spec/direct.md'),
  'docs/spec/feature.md': require('../docs/spec/feature.md'),
  'docs/spec/font.md': require('../docs/spec/font.md'),
  'docs/spec/introduce.md': require('../docs/spec/introduce.md'),
  'docs/spec/invitation.md': require('../docs/spec/invitation.md'),
  'docs/spec/layout/index.md': require('../docs/spec/layout/index.md'),
  'docs/spec/lightweight.md': require('../docs/spec/lightweight.md'),
  'docs/spec/motion.md': require('../docs/spec/motion.md'),
  'docs/spec/principle.md': require('../docs/spec/principle.md'),
  'docs/spec/proximity.md': require('../docs/spec/proximity.md'),
  'docs/spec/reaction.md': require('../docs/spec/reaction.md'),
  'docs/spec/repetition.md': require('../docs/spec/repetition.md'),
  'docs/spec/stay.md': require('../docs/spec/stay.md'),
  'docs/spec/transition.md': require('../docs/spec/transition.md'),
  'docs/spec/typography.md': require('../docs/spec/typography.md'),
};