webpackJsonp([169,211],{

/***/ 713:
/***/ function(module, exports) {

	module.exports = {
	  "content": [
	    "section",
	    [
	      "p",
	      "通过鼠标或键盘，输入范围内的数值。"
	    ],
	    [
	      "h2",
	      "何时使用"
	    ],
	    [
	      "p",
	      "当需要获取标准数值时。"
	    ]
	  ],
	  "meta": {
	    "category": "Components",
	    "subtitle": "数字输入框",
	    "type": "Data Entry",
	    "title": "InputNumber",
	    "filename": "components/input-number/index.zh-CN.md"
	  },
	  "toc": [
	    "ul",
	    [
	      "li",
	      [
	        "a",
	        {
	          "className": "bisheng-toc-h2",
	          "href": "#何时使用"
	        },
	        "何时使用"
	      ]
	    ],
	    [
	      "li",
	      [
	        "a",
	        {
	          "className": "bisheng-toc-h2",
	          "href": "#API"
	        },
	        "API"
	      ]
	    ]
	  ],
	  "api": [
	    "section",
	    [
	      "h2",
	      "API"
	    ],
	    [
	      "p",
	      "属性如下"
	    ],
	    [
	      "table",
	      [
	        "thead",
	        [
	          "tr",
	          [
	            "th",
	            "成员"
	          ],
	          [
	            "th",
	            "说明"
	          ],
	          [
	            "th",
	            "类型"
	          ],
	          [
	            "th",
	            "默认值"
	          ]
	        ]
	      ],
	      [
	        "tbody",
	        [
	          "tr",
	          [
	            "td",
	            "min"
	          ],
	          [
	            "td",
	            "最小值"
	          ],
	          [
	            "td",
	            "number"
	          ],
	          [
	            "td",
	            "-Infinity"
	          ]
	        ],
	        [
	          "tr",
	          [
	            "td",
	            "max"
	          ],
	          [
	            "td",
	            "最大值"
	          ],
	          [
	            "td",
	            "number"
	          ],
	          [
	            "td",
	            "Infinity"
	          ]
	        ],
	        [
	          "tr",
	          [
	            "td",
	            "value"
	          ],
	          [
	            "td",
	            "当前值"
	          ],
	          [
	            "td",
	            "number"
	          ],
	          [
	            "td"
	          ]
	        ],
	        [
	          "tr",
	          [
	            "td",
	            "step"
	          ],
	          [
	            "td",
	            "每次改变步数，可以为小数"
	          ],
	          [
	            "td",
	            "number",
	            "|",
	            "string"
	          ],
	          [
	            "td",
	            "1"
	          ]
	        ],
	        [
	          "tr",
	          [
	            "td",
	            "defaultValue"
	          ],
	          [
	            "td",
	            "初始值"
	          ],
	          [
	            "td",
	            "number"
	          ],
	          [
	            "td"
	          ]
	        ],
	        [
	          "tr",
	          [
	            "td",
	            "onChange"
	          ],
	          [
	            "td",
	            "变化回调"
	          ],
	          [
	            "td",
	            "Function"
	          ],
	          [
	            "td"
	          ]
	        ],
	        [
	          "tr",
	          [
	            "td",
	            "disabled"
	          ],
	          [
	            "td",
	            "禁用"
	          ],
	          [
	            "td",
	            "boolean"
	          ],
	          [
	            "td",
	            "false"
	          ]
	        ],
	        [
	          "tr",
	          [
	            "td",
	            "size"
	          ],
	          [
	            "td",
	            "输入框大小"
	          ],
	          [
	            "td",
	            "string"
	          ],
	          [
	            "td",
	            "无"
	          ]
	        ]
	      ]
	    ]
	  ]
	};

/***/ }

});